export default {

  //wallet
  WALLET_CREATED: 'WALLET_CREATED',
  CREATED_WALLET : 'CREATED_WALLET',
  ADDRESS: 'ADDRESS',

  CRYPOCURRENCY: 'BNB',
  CURRENCY : 'BUSD',
  SHARE_CURRENCY : 'VBUSD',


  QUEUE: 'QUEUE',
  BACKGROUND_QUEUE: 'BACKGROUND_QUEUE',
 

  //cooperatives
  ALL_COOPORATIVE_CYCLES_BY_CREATOR : 'ALL_COOPORATIVE_CYCLES_BY_CREATOR',
  IS_COOPORATIVE_MEMBER : 'IS_COOPORATIVE_MEMBER',
  COOPERATIVE_CONTRIBUTION : 'COOPERATIVE_CONTRIBUTION',
  PRICE_PER_POOL_SHARE : 'PRICE_PER_POOL_SHARE',


  //Groups
  SINGLE_GROUP_ESUSU : 'SINGLE_GROUP_ESUSU',
  SINGLE_GROUP_COOPORATIVE : 'SINGLE_GROUP_COOPORATIVE',

  //esusu
  ALL_ESUSU_CYCLES_BY_GROUPID : 'ALL_ESUSU_CYCLES_BY_CREATOR',
  IS_ESUSU_MEMBER : 'IS_ESUSU_MEMBER',
  ESUSU_CONTRIBUTIONS : 'ESUSU_CONTRIBUTIONS',

  //individual
  FLEXIBLE_DEPOSIT_RECORD : 'FLEXIBLE_DEPOSIT_RECORD',


  CYCLES_DISPLAY_STATUS: {
    PENDING: 'pending',
    ACTIVE: 'active',
    ENDED: 'ended',
    ALL: 'all',
  },

  EVENTS: {
    CREATE_ESUSU_EVENT: 'CreateEsusuCycleEvent',
  },

  LEADERBOARD: "LEADERBOARD_DATA"
};
