// export default {

//     //loader 
//     QUEUE : "QUEUE",

//     //admin login
//     IS_ADMIN_LOGIN_SUCCESSFUL : 'IS_ADMIN_LOGIN_SUCCESSFUL',

//     //USERS
//     GET_ALL_USERS : 'GET_ALL_USERS',
//     GET_USER_BY_ID : "GET_USER_BY_ID",
//     USER_BALANCE : "USER_BALANCE",
//     WALLET_CONNECTED : "WALLET_CONNECTED",
//     ADDRESS : "ADDRESS",

//     //deposit
//     DEPOSIT_SUCCESSFUL : 'DEPOSIT_SUCCESSFUL',
//     DEPOSIT_TRANSACTION_HISTORY : 'DEPOSIT_TRANSACTION_HISTORY',

//     //withdrawal
//     WITHDRAWAL_TRANSACTION_HISTORY : 'WITHDRAWAL_TRANSACTION_HISTORY',
   
//     //prices

// }
 let _const =   {

    //loader 
    QUEUE : "QUEUE",

    //admin login
    IS_ADMIN_LOGIN_SUCCESSFUL : 'IS_ADMIN_LOGIN_SUCCESSFUL',

    //USERS
    GET_ALL_USERS : 'GET_ALL_USERS',
    GET_USER_BY_ID : "GET_USER_BY_ID",
    USER_BALANCE : "USER_BALANCE",
    WALLET_CONNECTED : "WALLET_CONNECTED",
    ADDRESS : "ADDRESS",

    //deposit
    DEPOSIT_SUCCESSFUL : 'DEPOSIT_SUCCESSFUL',
    DEPOSIT_TRANSACTION_HISTORY : 'DEPOSIT_TRANSACTION_HISTORY',

    //withdrawal
    WITHDRAWAL_TRANSACTION_HISTORY : 'WITHDRAWAL_TRANSACTION_HISTORY',
   
    //prices

}
export default _const;